# Spanish text for es/ pages: citations (SRC_ES, one entry per SRC key; document titles keep their
# original language) and display labels. Sourced by R/site_data.R when options(site.lang = "es").
LANG_ES <- c(Spanish = "Español", Mandarin = "Mandarín", Japanese = "Japonés", Russian = "Ruso", Vietnamese = "Vietnamita")
SCENARIOS_ES <- c(sq = "Situación actual", a = "Escenario A", b = "Escenario B")
tr_lang <- function(x) unname(ifelse(x %in% names(LANG_ES), LANG_ES[x], x))

SRC_ES <- list(
  profiles = sprintf("PPS, *Enrollment Details for Language Immersion Schools* (Language Immersion Track Profiles), octubre de 2021 a octubre de 2025 ([actual](%s), [archivo](%s))", PPS_REPORTS, PPS_ARCHIVE),
  by_grade = sprintf("PPS, *Enrollment by Grade and Program Type*, octubre de 2024 y octubre de 2025 ([PPS Data & Reporting](%s))", PPS_REPORTS),
  by_lang = sprintf("PPS, *Enrollment by Language and School*, octubre de 2024 y octubre de 2025 ([PPS Data & Reporting](%s))", PPS_REPORTS),
  lottery = sprintf("PPS Enrollment & Transfer, *Elementary School / Kindergarten Lottery Results Summary*, sorteos de 2022-23 a 2026-27 ([resultados de sorteos anteriores](%s))", PPS_LOTTERY),
  lottery26 = sprintf("PPS Enrollment & Transfer, *2026-27 Kindergarten Lottery Results Summary* ([resultados de sorteos anteriores](%s))", PPS_LOTTERY),
  class_size = sprintf("PPS, *Class Size Detail*, 2021-22 a 2025-26 ([archivo](%s), [actual](%s))", PPS_ARCHIVE, PPS_REPORTS),
  district_k = sprintf("matrícula del distrito por grado: PPS, *Enrollment – Summary Comparison*, 3 de octubre de 2022 ([archivo](%s)), y *Enrollment by Grade and Program Type*, 2024 y 2025", PPS_ARCHIVE),
  scenarios = "Documentos de la Junta Educativa de PPS para el 6 de octubre de 2026: mapas de los escenarios y memorando *Rightsizing Update: Scenario Release*, digitalizados y transcritos en [pps-explorer](https://github.com/browniefed/pps-explorer) por Jason Brown",
  acs = "Oficina del Censo de EE. UU., Encuesta sobre la Comunidad Estadounidense (American Community Survey), estimaciones de 5 años 2020–2024, tablas C16001 y B16007, secciones censales (*tracts*) de los condados de Multnomah, Washington y Clackamas",
  blocks = "Oficina del Censo de EE. UU., datos de redistribución del Censo 2020 (P.L. 94-171), tablas P1 y P3, manzanas censales (*blocks*)",
  slide44 = "Junta Educativa de PPS, *10/06/26 PowerPoint*, diapositiva 44, \"Balance and Impact: Kindergarten – 8th Grade Students Who Move\" ([BoardBook](https://meetings.boardbook.org/Documents/DownloadPDF/14511742?org=915))",
  memo = "PPS, memorando a la Junta *Rightsizing Update: Scenario Release*, 5 de octubre de 2026, págs. 1–2 ([BoardBook](https://meetings.boardbook.org/Documents/DownloadPDF/14509719?org=915))",
  closures = "cierres de escuelas y escuelas receptoras: mapas de los escenarios y memorando de PPS (octubre de 2026), transcritos en [pps-explorer](https://github.com/browniefed/pps-explorer)",
  demographics = sprintf("PPS, *School/Neighborhood Enrollment by Ethnicity & Program*, octubre de 2025 (filas School; [PPS Data & Reporting](%s))", PPS_REPORTS),
  audit = "Green, T. L., & Hanson, H. (2026, 10 de junio). *Equity audit evaluation of Portland Public Schools' Southeast Enrollment and Program Balancing*",
  tle0908 = "Comité de Enseñanza, Aprendizaje e Inscripción (Teaching, Learning, and Enrollment Committee) de la Junta Educativa de PPS, 8 de septiembre de 2026, en 33:22 ([video](https://www.youtube.com/watch?v=S-pk57P6f_o&t=2002s); transcripción automática de [Save PDX Schools](https://savepdxschools.org/transcripts/))",
  summary10 = "PPS, *October 2025 Enrollment Summary, 10-year detail*, nota 6 (\"Bridger Spanish Immersion moved to Lent\")",
  psu_premove = sprintf("Portland State University Population Research Center, *Portland Public Schools Enrollment Forecasts*, ediciones 2022-23, 2023-24 y 2026-27 (Apéndice C / Tabla 5.5; [archivo](%s))", PPS_ARCHIVE),
  guides = "PPS, guías de las escuelas *How Could Your School Be Impacted?* (\"PPS Family-Friendly School Guide\", un PDF por escuela con fecha del 8 de octubre de 2026), página 4, matrícula proyectada de 2027-28 a 2031-32 ([página](https://www.pps.net/about/portland-public-schools-information/rightsize/how-could-your-school-be-impacted))",
  audit_schools = "Green, T. L., & Hanson, H. (2026, 29 de junio). *Equity audit evaluation of Portland Public Schools' Southeast Enrollment and Program Balancing initiative: School-by-school analysis* ([documentos del SEGC de PPS](https://www.pps.net/about/portland-public-schools-information/rightsize/segc-documents))",
  capture = sprintf("PPS, *Neighborhood Capture Rate Metrics* (Enrollment Summary by K-12 Students' Neighborhood and Type of School Attended), octubre de 2019 a octubre de 2025 ([actual](%s), [archivo](%s))", PPS_REPORTS, PPS_ARCHIVE),
  by_residence = sprintf("PPS, *School Enrollment by Neighborhood of Residence*, octubre de 2025 ([PPS Data & Reporting](%s))", PPS_REPORTS),
  isp = "Centro Nacional de Estadísticas Educativas (NCES), *Private School Universe Survey*, 2023-24 ([International School of Portland](https://nces.ed.gov/surveys/pss/privateschoolsearch/school_list.asp?Search=1&SchoolName=International+School+of+Portland&State=41)); número de estudiantes por grado según [US News](https://www.usnews.com/education/k12/oregon/international-school-of-portland-324304); idiomas según el [sitio web de la escuela](https://www.intlschool.org/about-us/about), consultado el 8 de octubre de 2026",
  lrfp = "PPS, *Long-Range Facility Plan 2021*, Volumen 1, pág. 53 (primaria) y pág. 57 (K-8), capacidad funcional ([PDF](https://www.pps.net/fs/resource-manager/view/84245cbd-4298-4803-8ba9-d26fb13a9c7a)); recopilado en [meub/pps-data](https://github.com/meub/pps-data) por Alex Meub (licencia MIT)",
  profiles25 = "PPS, *School Profiles*, 2025-26 (tablero de Power BI: capacidad funcional, porcentaje de uso, matrícula, certificación directa, tasa de captación; [página](https://www.pps.net/departments/dataaccountability/data-and-accountability/data-strategy-and-insights/internal-school-profiles)), obtenido el 9 de octubre de 2026",
  tle0908s = "Comité de Enseñanza, Aprendizaje e Inscripción (Teaching, Learning, and Enrollment Committee) de la Junta Educativa de PPS, 8 de septiembre de 2026, en 13:15 ([video](https://www.youtube.com/watch?v=S-pk57P6f_o&t=795s); transcripción automática de [Save PDX Schools](https://savepdxschools.org/transcripts/))",
  ode_assess = "Departamento de Educación de Oregon (ODE), *Assessment Group Reports* (resultados estatales, del distrito y de cada escuela por grupo de estudiantes; [página](https://www.oregon.gov/ode/educator-resources/assessment/Pages/Assessment-Group-Reports.aspx)), consultado el 9 de octubre de 2026",
  board1006 = "Junta Educativa de PPS, sesión ordinaria, 6 de octubre de 2026, presentación del personal en 2:25:37 ([video](https://www.youtube.com/watch?v=zOUH2Jq7Owo&t=8737s); transcripción automática de [Save PDX Schools](https://savepdxschools.org/transcripts/))",
  steele2017 = "Steele, J. L., Slater, R. O., Zamarro, G., Miller, T., Li, J., Burkhauser, S., & Bacon, M. (2017). Effects of dual-language immersion programs on student achievement: Evidence from lottery data. *American Educational Research Journal, 54*(1 suppl), 282S–306S ([doi](https://doi.org/10.3102/0002831216634463); [manuscrito de acceso abierto](https://files.eric.ed.gov/fulltext/ED577026.pdf)); resumen de RAND [RB-9903](https://www.rand.org/pubs/research_briefs/RB9903.html)",
  rand_impl = "Li, J. J., Steele, J. L., Slater, R., Bacon, M., & Miller, T. (2016). *Implementing two-way dual-language immersion programs: Classroom insights from an urban district* (resumen de investigación de RAND [RB-9921](https://www.rand.org/pubs/research_briefs/RB9921.html))",
  utah2021 = "Steele, J. L., Watzinger-Tharp, J., Slater, R. O., Roberts, G., & Bowman, K. (2021). *Achievement effects of dual language immersion in one-way and two-way programs: Evidence from a state scale-up in Utah* (documento de trabajo, University of Arkansas, [PDF](https://edre.uark.edu/_resources/pdf/Utah_DLI_2021Jan.pdf))",
  watzinger = "Watzinger-Tharp, J., Swenson, K., & Mayne, Z. (2018). Academic achievement of students in dual language immersion. *International Journal of Bilingual Education and Bilingualism, 21*(8), 913–928 ([doi](https://doi.org/10.1080/13670050.2016.1214675))",
  morales = "Morales, C. (2025). Dual language immersion programs and student achievement in early elementary grades. *Educational Evaluation and Policy Analysis, 47*(2), 616–623 ([doi](https://doi.org/10.3102/01623737241228829)); solo el resumen",
  bibler = "Bibler, A. J. Dual language education and student achievement. *Education Finance and Policy* ([doi](https://doi.org/10.1162/edfp_a_00320); citas del [documento de trabajo](https://economics.nd.edu/assets/187323/paper_dual_language_education_bibler_1_19.pdf) de 2016, pág. 6)",
  cal = "Howard, E. R., Lindholm-Leary, K. J., Rogers, D., Olague, N., Medina, J., Kennedy, D., Sugarman, J., & Christian, D. (2018). *Guiding principles for dual language education* (3rd ed.). Center for Applied Linguistics ([editorial](https://www.cal.org/publications/guiding-principles-3/))",
  cabe = "California Association for Bilingual Education, *Dual Language Immersion Planning Guide*, \"Implementation model\" ([página](https://di.gocabe.org/get-started/pedagogical-decisions/implementation-model)), consultado el 9 de octubre de 2026",
  freire = "Freire, J. A., & Alemán, E., Jr. (2021). \"Two schools within a school\": Elitism, divisiveness, and intra-racial gentrification in a dual language strand. *Bilingual Research Journal, 44*(2), 249–269 ([doi](https://doi.org/10.1080/15235882.2021.1942325)); resumen",
  dejong = "de Jong, E. J., & Bearse, C. I. (2014). Dual language programs as a strand within a secondary school: Dilemmas of school organization and the TWI mission. *International Journal of Bilingual Education and Bilingualism, 17*(1), 15–31 ([doi](https://doi.org/10.1080/13670050.2012.725709)); resumen",
  nasem = "National Academies of Sciences, Engineering, and Medicine. (2017). *Promoting the educational success of children and youth learning English: Promising futures*, cap. 8, pág. 300 ([leer en línea](https://nap.nationalacademies.org/read/24677/chapter/10))",
  methods = "Detalles del método: [Fuentes y métodos](methods.qmd)"
)
